{% set name = "wiutils" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wiutils-{{ version }}.tar.gz
  sha256: af1a735fac216099ed6f19a727883b571d94dd693f4be044cdf5e4db17c954f9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ffmpeg-python
    - matplotlib-base
    - numpy
    - opencv
    - openpyxl
    - pandas
    - pillow
    - python >=3.6
    - seaborn

test:
  imports:
    - wiutils
  requires:
    - pip

about:
  home: https://github.com/PEM-Humboldt/wiutils
  summary: Exploration utilities for Wildlife Insights projects.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcelovilla
