{% set name = "wiutils" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wiutils-{{ version }}.tar.gz
  sha256: 1750706d6cdd999b4952649dd2264e81966e2734375f3850f9a8e7fd09cf8940

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ffmpeg-python
    - numpy
    - opencv
    - openpyxl
    - pandas
    - pillow
    - python >=3.6

test:
  imports:
    - wiutils
  requires:
    - pip

about:
  home: https://github.com/PEM-Humboldt/wildlife-insights-utils
  summary: Transformation and exploration utilities for information downloaded from Wildlife Insights projects.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcelovilla
